# ~/.tmuxinator/config.yml
# tmux session for configuring my env
# you can make as many tabs as you wish...

project_name: config
project_root: ~/
# rvm: --use default
tabs:
  - editor: vim
  - shell:
  - shell:
